### ISSUE TITLE
MissingRequiredParameterException: An error occurred (MissingParameter) when calling the PutMetricData operation: The parameter MetricData is required.

### ISSUE THREAD

**Issue by spireluis** [awslabs/cloudwatch-fluent-metrics#13]
Hi there,

I'm getting:
```
An error occurred (MissingParameter) when calling the PutMetricData operation: The parameter MetricData is required.: MissingRequiredParameterException
Traceback (most recent call last):
File "/var/task/spire/__init__.py", line 13, in decorated_function
res = func(*args, **kwargs)
File "/var/task/program_engine/user_event_engine.py", line 51, in handle
program_engine.check_events(list(user_events))
File "/var/task/program_engine/engine.py", line 194, in check_events
self.metric.flush()
File "/var/task/libs/fluentmetrics/buffer.py", line 73, in flush
FluentMetric._record_metric(self, page)
File "/var/task/libs/fluentmetrics/metric.py", line 368, in _record_metric
MetricData=metric_data,
File "/var/runtime/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/var/runtime/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
MissingRequiredParameterException: An error occurred (MissingParameter) when calling the PutMetricData operation: The parameter MetricData is required.
```
When using BufferedFluentMetric, my guess at the moment is that if all the data in the buffers has been sent, i.e.: page is None here:

```
"libs/fluentmetrics/buffer.py" line 26 of 87 --29%-- col 1
   53     def flush(self, send_partial = True):
   54         '''Sends as much data as possible to CloudWatch. If send_partial is set to False,
   55         this only sends full pages. This way, it minimizes the API usage at the cost of
   56         delaying data.
   57         '''
   58         for namespace, buffer in self.buffers.items():
   59             full_pages = len(buffer) / PAGE_SIZE
   60             for i in range(full_pages):
   61                 start = i * PAGE_SIZE
   62                 end = (i + 1) * PAGE_SIZE
   63                 page = buffer[start:end]
   64
   65                 # ship it
   66                 FluentMetric._record_metric(self, page)
   67
   68             start = full_pages * PAGE_SIZE
   69             end = len(buffer) % PAGE_SIZE
   70             if send_partial:
   71                 # ship remaining items
   72                 page = buffer[start:end]
   73                 FluentMetric._record_metric(self, page)
```
and 
```
"libs/fluentmetrics/metric.py" line 368 of 374 --98%-- col 14
364     def _record_metric(self, metric_data):
365         logger.debug('log: {}'.format(metric_data))
366         self.client.put_metric_data(
367                 Namespace=self.namespace,
368                 MetricData=metric_data,
369         )
```
MetricData=metric_data, is None then, which is probably why the API complains back.

Got any better ideas about this? 

Thanks!

Luis

**Comment by troylar** [comment]
@spireluis Can you try this again and turn on debug logging?
